- name: Provisioning callback example 
  hosts: all
  vars:
    - var_1: "{{ variable_1 }}"
    - var_2: "{{ variable_2 }}"

  tasks:
  - name: Execute callback request
    debug:
      msg: "Hi! You are connecting from a '{{ var_1 }}' and saying '{{ var_2 }}' by a provisioning callback request."
   
