- hosts: rhel_roles
  vars:

    network_connections:
      - name: eth2
        interface_name: eth2
        type: ethernet
        mac: "08:00:27:f3:f6:ab"
        state: up
        autoconnect: yes
        ip:
          auto6: no
          route_metric6: -1
          address:
            - 10.0.0.40/24
    timesync_ntp_servers:
      - hostname: server 1.es.pool.ntp.org
        maxpoll: 6
      - hostname: server 2.europe.pool.ntp.org
        maxpoll: 6
      - hostname: server 1.europe.pool.ntp.org
        maxpoll: 6
    timesync_ptp_domains:
      - number: 0
        interfaces: [ eth1 ]
        transport: L2
        delay: 0.000010
      - number: 1
        interfaces: [ eth2 ]
        transport: UDPv4
        delay: 0.000010
    selinux_policy: targeted
    selinux_state: permissive
    core_collector: "makedumpfile -l --message-level 2 -d 31 -c"
    path: /var/crash
    system_action: reboot # reboot | halt | poweroff | shell
      
  roles:
    - { role: linux-system-roles.network, become: yes }
    - { role: linux-system-roles.timesync, become: yes }
    - { role: linux-system-roles.selinux, become: yes }
    - { role: linux-system-roles.kdump, become: yes }