- name: Test
  hosts: all
  collections:
    - ovirt.ovirt
  vars:
    ovirt_password: RH1q2w3eZxc,.-
  tasks:

    #- ansible.builtin.include_vars: 
    #   file: ovirt_password.yml

  - name: Obtain SSO token with using username/password credentials
    ovirt.ovirt.ovirt_auth:
      url: https://lab-rhevm.gsslab.brq.redhat.com/ovirt-engine/api/v4
      username: rafsanch
      ca_file: ca.pem
      password: "{{ ovirt_password }}"
    register: ovirt_auth

  - debug:
      msg: "{{ ovirt_auth }}"

  # Previous task generated I(ovirt_auth) fact, which you can later use
  # in different modules as follows:
  - ovirt.ovirt.ovirt_vm:
      auth: "{{ ovirt_auth }}"
      state: absent
      name: myvm


  - name: Always revoke the SSO token
    ovirt.ovirt.ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"
