- name: Sample
  hosts: all
  #become: yes
  tasks:
    - name: Message
      debug:
        msg: "{{ foreman_params.rafa }}"
    - debug:
        msg: "{{ item }}"
      with_items: "{{ lookup('vars','foreman_params') }}"
      when: item == "rafa" 
