- name: Sample
  hosts: all
  #become: yes
  tasks:
    - name: Message
      debug:
        msg: "{{ foreman_params.rafa }}"
    - debug:
        msg: "{{ lookup('vars','foreman_params.[0].rafa') }}"
