- name: Sample
  hosts: all
  vars:
    message: "The first message"
  tasks:
    - name: URI
      uri:
        url: https://foaas.com/asshole/:rafa
        return_content: yes
      register: response
    - debug:
        msg: "{{ response }}"
    - shell: export
      register: variables
    - debug:
        msg: "{{ variables }}"
    - shell: ip route | grep default
      register: gateway
    - debug:
        msg: "{{ gateway }}"
