- name: Sample
  hosts: all
  vars:
    message: "The first message"
  tasks:
    - name: URI
      #environment:
      #  no_proxy: "foaas.com"
      uri:
        url: https://foaas.com/cool/:rafa
        return_content: yes
        use_proxy: no
        headers:
          Content-Type: application/json
          Accept: application/json
      register: response
    - debug:
        msg: "{{ response }}"
    - shell: export
      register: variables
    - debug:
        msg: "{{ variables }}"
    - shell: ip route | grep default
      register: gateway
    - debug:
        msg: "{{ gateway }}"
