- name: Where I am
  hosts: all
  tasks:
    - name: Where I am
      shell: ip add | grep eth0 | grep inet | awk '{print $2}'
      register: host
      delegate_to: localhost
      
    - name: Print results
      debug:
        msg: "{{ host }}"
        
    - name: Export
      shell: export
      register: export
      
    - debug:
        msg: "{{ export }}"
