---
- hosts: 192.168.100.147
  vars:
    - ansible_connection: winrm
    - ansible_winrm_transport: ntlm
    - ansible_port: 5986
    - ansible_winrm_server_cert_validation: ignore

  tasks:

    - name: Install notepad++
      win_chocolatey:
        name: notepadplusplus
