---
- hosts: all
  vars:
    - ansible_connection: winrm
    - ansible_winrm_transport: ntlm
    - ansible_port: 5986

  tasks:

    - name: Install notepad++
      win_chocolatey:
        name: notepadplusplus
